version = 0.1
[default]
[default.global.parameters]
stack_name = "photo-blog-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "photo-blog-app"
region = "us-east-1"
parameter_overrides = "Environment=\"dev\" DomainName=\"dev.mscv2group3.link\" PrimaryRegion=\"us-east-1\" BackupRegion=\"us-west-2\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[dev]
[dev.global.parameters]
stack_name = "photo-blog-app-dev"

[dev.deploy.parameters]
parameter_overrides = "Environment=\"dev\" DomainName=\"dev.mscv2group3.link\" PrimaryRegion=\"us-east-1\" BackupRegion=\"us-west-2\""
s3_prefix = "photo-blog-app-dev"

[prod]
[prod.global.parameters]
stack_name = "photo-blog-app-prod"

[prod.deploy.parameters]
parameter_overrides = "Environment=\"prod\" DomainName=\"mscv2group1.link\" PrimaryRegion=\"us-east-1\" BackupRegion=\"us-west-2\""
s3_prefix = "photo-blog-app-prod"
confirm_changeset = true