version = 0.1

[dev]
[dev.deploy.parameters]
stack_name = "photo-blog-app-dev"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "photo-blog-app"
region = "eu-central-1"
cached = true
parallel = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\" DomainName=\"dev.mscv2group3.link\" PrimaryRegion=\"eu-central-1\" BackupRegion=\"eu-west-1\""

[prod]
[prod.deploy.parameters]
stack_name = "photo-blog-app-prod"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "photo-blog-app-prod"
region = "eu-central-1"
cached = true
parallel = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"prod\" DomainName=\"mscv2group3.link\" PrimaryRegion=\"eu-central-1\" BackupRegion=\"eu-west-1\""