version = 0.1

[auth.deploy.parameters]
stack_name = "photo-blog-app-auth-dev"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "photo-blog-app-auth"
region = "eu-central-1"
cached = true
parallel = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" DomainName=\"mscv2group3.link\" SharedLayerArn=\"{{resolve:ssm:/photo-blog-app/dev/shared-layer}}\""

[auth.build.parameters]
cached = true
parallel = true
template_file = "template.yaml"


# TO USE THIS FILE TO DEPLOY YOUR INDEPENDENT SERVICE, run the following commands the project's root directory:
#
# cd services/authentication
# sam validate && sam validate --lint
# sam build --config-file deploy.toml --config-env auth
# sam deploy --config-file deploy.toml --config-env auth