version = 0.1

[image-processing.deploy.parameters]
stack_name = "photo-blog-app-image-processing-dev"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "photo-blog-app-image-processing"
region = "eu-central-1"
cached = true
parallel = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" ProcessedBucketName=\"{{resolve:ssm:/photo-blog-app/dev/processed-bucket}}\" SharedLayerArn=\"{{resolve:ssm:/photo-blog-app/dev/shared-layer}}\""

[image-processing.build.parameters]
cached = true
parallel = true
template_file = "template.yaml"


# TO USE THIS FILE TO DEPLOY YOUR INDEPENDENT SERVICE, run the following commands the project's root directory:
#
# cd services/image-processing
# sam validate && sam validate --lint
# sam build --config-file deploy.toml --config-env image-processing
# sam deploy --config-file deploy.toml --config-env image-processing